# -*- coding: utf-8 -*-
"""Cópia de python_para_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIpjwT-bllSJ2nr_gtzQ-wXN4KNxN2eW

# **INTRODUÇÃO À PYTHON PARA DADOS**

**VARIÁVEIS E TIPOS DE DADOS**

Variáveis são como caixas onde guardamos informações, e cada informação tem um tipo de dado (como número, texto, lista...).
Vamos ver como declarar variáveis e como diferentes tipos de dados funcionam, usando exemplos da série "The Big Bang Theory".

**String (str)** <p>
Explicação: Strings são sequências de caracteres que representam texto. Em Python, strings são definidas entre aspas (" ou ').
Elas são usadas para armazenar palavras, frases ou qualquer tipo de dado textual.

**Inteiro (int)** <p>
Explicação: Inteiros são números sem casas decimais. Eles podem ser usados para representar contagens, índices ou qualquer valor numérico que não precisa de precisão decimal.

**Float (números decimais)** <p>
Explicação: Floats são números que incluem casas decimais.
Eles são usados quando precisamos de maior precisão, como para avaliações, medições ou valores financeiros.

**Booleano (bool)** <p>
Explicação: Booleanos são variáveis que podem ter apenas dois valores: True (verdadeiro) ou False (falso).
Eles são usados para representar estados binários, como "ligado/desligado" ou "verdadeiro/falso".

**Lista (list)** <p>
Explicação: Listas são coleções ordenadas de elementos que podem ser de qualquer tipo.<p>
Em Python, listas são definidas entre colchetes ( [ ] ). Você pode adicionar, remover e acessar elementos dentro de uma lista.

**Dicionário (dict)**<p>
Explicação: Dicionários são coleções de pares de chave e valor, onde cada chave é única. <p>
Em Python, dicionários são definidos entre chaves ( { } ). Eles são usados para mapear uma chave a um valor, como um nome a uma idade.
"""

# dicionário
sheldon = {
    "nome": "Sheldon Cooper",
    "idade": 30,
    "profissao": "Físico Teórico",
    "q_i": 187
}

"""**Tupla (tuple)**<p>
Explicação: Tuplas são coleções ordenadas e imutáveis de elementos.<p>
Ao contrário das listas, os valores dentro de uma tupla não podem ser alterados após a sua criação.<p>
Tuplas são definidas entre parênteses ( ( ) ).

"""

# tupla
curiosidades = (
    "Bazinga!",
    "Elevador quebrado",
    "Contrato de colegas de quarto"
)

"""**Conjunto (set)**<p>
Explicação: Conjuntos são coleções não ordenadas de elementos únicos. Em Python, conjuntos são definidos entre chaves ( { } ).<p>
Eles são úteis quando você precisa garantir que não haja elementos duplicados.
"""

# conjunto (set)
profissao_personagens = {
    "Físico",
    "Engenheiro",
    "Cientista",
    "Atriz",
    "Neurobiologista"
}

"""**ESTRUTURA DE DADOS**

Aqui vamos explorar as estruturas de dados, que são formas de organizar e armazenar dados.<p>
Vamos trabalhar com listas, que guardam múltiplos valores em ordem; e dicionários, que guardam pares de chave e valor.

**.append()**<p>
O método append é usado para adicionar um novo elemento ao final da lista.<p> Neste caso, Haward é adicionado à lista de personagens.
"""

# lista dos personagens principais com append
personagens = [
    "Sheldon",
    "Leonard",
    "Penny",
    "Amy",
    "Raj",
    "Bernadette"
]
personagens.append("Howard") # Adicionando um personagem à lista
print(personagens)

"""**.remove()**<p>
O método remove é usado para deletar um  elemento da lista.<p>
Neste caso, Raj é deletado da lista de personagens.
"""

# lista dos personagens principais com remove
personagens = [
    "Sheldon",
    "Leonard",
    "Penny",
    "Amy",
    "Raj",
    "Bernadette"
]
personagens.remove("Raj") # Removendo um personagem da lista
print(personagens)

"""**acessar valor associado a chave**<p>
A linha print(sheldon["nome"]) acessa o valor associado à chave "nome" e imprime "Sheldon Cooper".
"""

# dicionário com acesso ao valor de uma chave específica
sheldon = {
    "nome": "Sheldon Cooper",
    "idade": 30,
    "profissao": "Físico Teórico"
}
print(sheldon["nome"]) # Acessando o valor de uma chave específica

"""**CONDICIONAIS E LOOPS**<p>
Nesta parte, vamos aprender como tomar decisões e repetir ações no código usando condicionais e loops.<p>
Condicionais (if-else) permitem executar código apenas se uma condição for verdadeira. Loops (for e while) permitem repetir uma ação várias vezes.

**Condicional (if)**<p>
Objetivo: Verificar se o número de temporadas é maior que 15.<p>
Como funciona: Se a variável 'temporadas' for maior que 15, o código dentro do bloco if será executado e a mensagem será impressa. Caso contrário, o código dentro do bloco if será ignorado.<p>
Neste exemplo: A condição temporadas > 15 é falsa, pois o valor de temporadas é 12. Portanto, a mensagem "The Big Bang Theory é uma série muito longa com 12 temporadas!" não será impressa.

**Condicional (elif)**<p>
Objetivo: Verificar se o número de temporadas é maior que 10, mas não maior que 15.<p>
Como funciona: O bloco elif é uma parte do controle de fluxo que ocorre após uma condição if inicial. Se a condição if não for satisfeita, o código verifica a condição elif. No caso, se temporadas for maior que 10 e não maior que 15, a mensagem será impressa.<p>
Neste exemplo: A condição temporadas > 10 é verdadeira para o valor 12 de temporadas. Assim, a mensagem "The Big Bang Theory é uma série longa com 12 temporadas!" será exibida.<p>

**Condicional (else)**<p>
Objetivo: Capturar casos em que nenhuma das condições anteriores (if ou elif) for verdadeira.<p>
Como funciona: O bloco else é executado quando todas as condições anteriores (if e elif) são falsas. Se nenhuma das condições no if e elif for satisfeita, o código dentro do bloco else será executado.<p>
Neste Exemplo: O bloco else será executado somente se a condição if (por exemplo, temporadas > 15) e a condição elif (por exemplo, temporadas > 10) forem falsas. No caso em questão, o bloco elif é verdadeiro porque temporadas é 12, que é maior que 10. Portanto, a mensagem "The Big Bang Theory é uma série longa com 12 temporadas!" será impressa e o bloco else não será executado.

**Loop (for)**<p>
Objetivo: Iterar sobre uma sequência (como uma lista, tupla, string, ou intervalo de números) e executar um bloco de código para cada item na sequência.<p>
Como funciona: O loop for percorre cada elemento da lista personagens, atribuindo o valor atual à variável personagem e executando o bloco de código (neste caso, imprimindo o nome do personagem).<p>
Quando usar: Use for quando você sabe de antemão quantas vezes deseja iterar, como quando está iterando sobre uma coleção de itens ou um intervalo específico de números.

**Loop (while)**<p>
Condição: O loop continua executando enquanto episodios_assistidos for menor que episodios_por_temporada.<p>
Ação: A cada iteração, o número de episódios assistidos é incrementado em 1, e o episódio correspondente é impresso.<p>
Neste exemplo, o loop while é usado para simular a contagem dos episódios que Sheldon assiste. A cada iteração do loop, um episódio é contado até que Sheldon tenha assistido todos os episódios da primeira temporada.

**MÉTODOS E FUNÇÕES**<p>
Métodos são funções que estão associadas a um objeto ou classe específicos e operam nos dados desse objeto.<p>
Enquanto funções podem existir de forma independente, métodos fazem parte de uma classe ou objeto e geralmente manipulam ou interagem com os atributos desse objeto.

**Método: lower**<p>
Este método transforma todas as letras da string serie em minúsculas.
"""

# usando o método lower para transformar o nome da série em letras minúsculas
serie_minuscula = serie.lower()
print(serie_minuscula)

"""**Método: upper**<p>
Este método transforma todas as letras da string serie em maiúsculas.
"""

# usando o método upper para transformar o nome da série em letras maiúsculas
serie_maiuscula = serie.upper()
print(serie_maiuscula)

"""**Função**<p>
Objetivo: A função recebe dois parâmetros: temporadas e episodios_por_temporada.<p>
Cálculo: Multiplica o número de temporadas pelo número médio de episódios por temporada para calcular o total de episódios.<p>
A função é chamada usando os valores das variáveis temporadas e episodios_por_temporada que foram definidos anteriormente.<p>
O resultado é armazenado na variável total.

**O Que é def?**?<p>
Definição de Função: def é uma palavra-chave que indica o início da definição de uma função.<p>Quando você usa def, está dizendo ao Python que você está prestes a criar uma nova função.

## **EXERCÍCIOS**

**Exercício 1: Variáveis e Tipos de Dados**<p>
Objetivo: Trabalhar com diferentes tipos de variáveis e exibir informações.<p>

*Instruções*:
1. Crie variáveis para armazenar informações sobre uma série fictícia:
nome_serie (string)<p>
ano_lancamento (int)<p>
temporadas (int)<p>
avaliacao (float)<p>
em_andamento (booleano)<p>
2. Crie uma variável de lista para armazenar os nomes dos principais personagens da série.<p>

3. Imprima uma mensagem formatada que exiba todas essas informações.
"""

# Crie uma variável chamada nome_serie e armazene o nome de uma série fictícia como uma string

nome_serie = "Seinfeld";

# Crie uma variável chamada ano_lancamento e armazene o ano de lançamento da série como um número inteiro

ano_lancamento = 1989;

# Crie uma variável chamada temporadas e armazene o número de temporadas da série como um número inteiro

temporadas = 9;

# Crie uma variável chamada avaliacao e armazene a avaliação da série como um número de ponto flutuante

avaliacao = 8.9;

# Crie uma variável chamada em_anda e armazene se a série ainda está em andamento como um valor booleano (True ou False)

em_anda = False;

# Crie uma variável chamada personagens que seja uma lista contendo os nomes dos principais personagens da série

personagens = ["Jerry", "Elaine", "Kramer", "Constanza"]

# Use print para exibir uma mensagem formatada que inclua todas essas variáveis e suas informações

print("A série " + nome_serie + " de " + str(ano_lancamento) + " tem " + str(temporadas) + " temporadas. " "A avaliação no IMDB é de " + str(avaliacao) + ". Os personagens principais são " + ",".join(personagens))

print(f"A série {nome_serie} de {ano_lancamento} tem {temporadas} temporadas. A avaliação no IMDB é de {avaliacao}. Os personagens principais são {', '.join(personagens)}.")



"""**Exercício 2: Condicionais**<p>
Objetivo: Utilizar condicionais para verificar e responder a diferentes condições.<p>

*Instruções:*<p>
1. Crie uma função chamada verificar_serie que receba a avaliação e o número de temporadas da série como parâmetros.<p>
2. A função deve:<p>
Imprimir uma mensagem se a avaliação for maior que 8.0.<p>
Imprimir uma mensagem se a série tiver mais de 10 temporadas.<p>
Imprimir uma mensagem padrão se nenhuma das condições acima for verdadeira.<p>
"""

# Crie uma função chamada verificar_serie que receba dois parâmetros:
# - avaliacao: a avaliação da série como um número de ponto flutuante
# - temporadas: o número de temporadas da série como um número inteiro


# Dentro da função, use uma estrutura condicional para verificar se a avaliação é maior que 8.0
# Se a condição for verdadeira, imprima uma mensagem informando que a série tem uma boa avaliação

def verificar_serie(avaliacao, temporada) :
  if avaliacao > 8.0:
    print(f"{nome_serie} tem uma boa avaliação!")

verificar_serie( avaliacao, temporadas)
# Use outra estrutura condicional para verificar se o número de temporadas é maior que 10
# Se a condição for verdadeira, imprima uma mensagem informando que a série tem muitas temporadas

def verificar_serie(avaliacao, temporada) :
  if temporada > 10:
    print(f"{nome_serie} teve muitas temporadas")
  else:
      print(f"{nome_serie} teve apenas {temporadas} temporadas")

verificar_serie(avaliacao, temporadas)

# Use um bloco else para imprimir uma mensagem padrão caso nenhuma das condições acima seja verdadeira
# Chame a função verificar_serie com valores de exemplo para teste

"""**Exercício 3: Loop for e while**<p>
Objetivo: Praticar o uso de loops para iterar sobre dados e realizar ações repetitivas.<p>

*Instruções:*<p>
1. Use um loop **for** para imprimir cada personagem da lista de personagens.<p>
2. Use um loop **while** para contar quantos episódios de uma temporada foram assistidos, simulando o processo de assistir aos episódios até o total definido.<p>
*Dicas:*<p>
No loop for, use a variável personagem para acessar cada item na lista personagens.<p>
No loop while, incremente a variável episodios_assistidos em cada iteração e imprima o número do episódio assistido até que o total de episódios seja alcançado.<p>
"""

# Crie uma lista chamada personagens contendo os nomes dos personagens

personagens = ["Jerry", "Elaine", "Kramer", "Constanza"]

print(personagens)
# Use um loop for para iterar sobre cada personagem na lista
# Dentro do loop, use a função print para exibir o nome de cada personagem
for personagem in personagens :
 print(personagem)


# Defina uma variável chamada episodios_assistidos e inicialize com 0
episodios_assistidos = 0;

# Defina uma variável chamada episodios_por_temporada com o total de episódios na temporada
episodios_por_temporada = 20;

# Use um loop while para simular o processo de assistir episódios
# O loop deve continuar enquanto episodios_assistidos for menor que episodios_por_temporada
# Dentro do loop, incremente episodios_assistidos em 1 e imprima o número do episódio assistido
# Após o loop, imprima uma mensagem informando que todos os episódios foram assistidos
while episodios_assistidos < episodios_por_temporada:
  episodios_assistidos += 1
  print(f"Episódio {episodios_assistidos} assistido.")

"""**Exercício 4: Funções e Métodos**<p>
Objetivo: Definir e utilizar funções para realizar cálculos e manipular dados.<p>

*Instruções:*<p>
1. Crie uma função chamada calcular_total_episodios que recebe dois parâmetros: temporadas e episodios_por_temporada.<p>
A função deve calcular o total de episódios multiplicando os dois parâmetros e retornar o resultado.<p>
2. Após definir a função, chame-a passando os valores das variáveis temporadas e episodios_por_temporada para obter o total de episódios.<p>
Armazene o resultado em uma variável chamada total e imprima uma mensagem que mostre o total de episódios.
"""

# Função para calcular o total de episódios
# Defina a função calcular_total_episodios com parâmetros temporadas e episodios_por_temporada
# A função deve retornar o produto desses dois parâmetros
def calcular_total_episodios(temporadas, episodios_por_temporada):
  return temporadas * episodios_por_temporada

  calcular_total_episodios(temporadas, episodios_por_temporada)


# Use a função para calcular o total de episódios
# Chame a função passando as variáveis temporadas e episodios_por_temporada
# Armazene o resultado em uma variável chamada total
# Imprima uma mensagem que exiba o total de episódios calculado

total = calcular_total_episodios(temporadas, episodios_por_temporada)
print(f"O total de episódio de {nome_serie} é {total}")

"""**Exercício 5: Manipulação de Dados**<p>
Objetivo: Praticar a manipulação de listas e dicionários, e usar loops para processar dados.<p>

*Instruções:*<p>
1. Criar uma Lista de Personagens e seus detalhes:<p>
Crie uma lista chamada detalhes_personagens onde cada item é um dicionário.<p>
Cada dicionário deve conter informações sobre um personagem, com chaves como "nome", "idade" e "profissao".<p>

2. Adicionar um Novo Personagem:<p>
Adicione um novo dicionário à lista com as informações de um novo personagem.<p>
Escolha um nome, idade e profissão diferentes dos que já estão na lista.<p>

3. Usar um Loop for:<p>
Use um loop for para percorrer a lista detalhes_personagens.<p>
Para cada dicionário na lista, imprima o nome do personagem, a idade e a profissão no formato:<p>
"Nome: [nome], Idade: [idade], Profissão: [profissao]".
"""

# Lista de dicionários com detalhes dos personagens
# Crie uma lista chamada detalhes_personagens
# Cada item da lista deve ser um dicionário contendo informações sobre o personagem
detalhes_personagens = [
    {'nome': 'Jerry Seinfeld', 'idade': 30 , 'profissao': 'comediante' },
    {'nome': 'Elaine Marie Benes', 'idade': 28, 'profissao': 'assistente pessoal'},
    {'nome': 'Cosmo Kramer', 'idade': 33, 'profissao': 'desempregado'}
    ]

# Adicione um novo personagem à lista
# Crie um dicionário com nome, idade e profissão, e adicione à lista detalhes_personagens
Constanza = {
    'nome': 'George Costanza',
    'idade': 30,
    'profissao': 'desempregado'
}

detalhes_personagens.append(Constanza)

# Loop for para imprimir detalhes dos personagens
# Use um loop for para percorrer cada dicionário na lista detalhes_personagens
for detalhe_personagem in detalhes_personagens:
 print(detalhe_personagem)

# Para cada dicionário, imprima as informações do personagem no formato:

# "Nome: [nome], Idade: [idade], Profissão: [profissao]"

"""♥ Obrigada por participarem da aula ♥

Qualquer dúvida sobre os exercícios ou algo a mais, estarei a disposição. <p>
Milene Martins - AI Engineer
"""